version: '3.4'

services:
  docker_vscode:
    image: docker_vscode
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8080
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 server.js